### ISSUE TITLE
Upload Documents

### ISSUE THREAD

**Issue by f3fora** [rschroll/rmfuse#13]
Do we have any chance to see a simple way to upload documents to rm_cloud using `rmcl`? 

Should a `mknod` in the `class RmApiFS(pyfuse3.Operations)` be implemented or an external tool be made?

Moreover, I think that the name of the class should be `rmFUSE` or whatever and also  `fuse_options.add('fsname=rmapi')` should be changed.

**Comment by rschroll** [comment]
Moving or copying documents into the mount directory will cause them to be uploaded.  (Though the upload will only succeed if the documents are PDF or EPUB files.)  In my testing, the relevant FUSE method seems to be `create`.  But if your system is calling `mknod`, we could make it do the same thing as `create`.

**Comment by f3fora** [comment]
Sorry... I was trying to upload some PDF in landscape orientation, and rmfuse do nothing. So I wrongly assume this feature was not implemented.

Maybe we can reproduce remarkable official applications which rotate the PDF to portrait before uploading to the cloud, or raise a warning.

**Comment by rschroll** [comment]
The orientation shouldn't be an issue.  If it's not uploading documents, that's a bug.  You can check out #6 for a branch with a lot more instrumentation about file uploads; that may give a clearer idea of what's going wrong.  (Run with `-v`.)  It will be merged into master soon.

**Comment by f3fora** [comment]
It's a bug in `master`, but it is already solved in `llfuse`.
Thanks.

**Comment by rschroll** [comment]
I've just merged llfuse into master, heading towards a release, so I'll go ahead and close this.
