### ISSUE TITLE
After logging in successfully I see no content

### ISSUE THREAD

**Issue by nikolaishields** [rschroll/rmfuse#43]
When running rmfuse, I see none of the content that is present in rmcloud/ my remarkable.

-v output
`
[nix-shell:~]$ rmfuse -v ~/remarkable
DEBUG:pyfuse3:Initializing pyfuse3
DEBUG:pyfuse3:Calling fuse_session_new
DEBUG:pyfuse3:Calling fuse_session_mount
DEBUG:rmfuse.fuse:Mounting on /home/nikolai/remarkable
DEBUG:pyfuse3:pyfuse-02: No tasks waiting, starting another worker (now 2 total).
DEBUG:pyfuse3:pyfuse-03: No tasks waiting, starting another worker (now 3 total).
DEBUG:rmcl.api:Renewing user token
DEBUG:pyfuse3:pyfuse-04: No tasks waiting, starting another worker (now 4 total).
DEBUG:pyfuse3:pyfuse-05: No tasks waiting, starting another worker (now 5 total).
DEBUG:pyfuse3:pyfuse-06: No tasks waiting, starting another worker (now 6 total).
DEBUG:rmcl.api:Renewing user token
DEBUG:pyfuse3:Calling fuse_session_unmount
DEBUG:pyfuse3:Calling fuse_session_destroy
`

-vv output
`FUSE library version: 3.10.5
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.35
flags=0x33fffffb
max_readahead=0x00020000
   INIT: 7.31
   flags=0x0040b039
   max_readahead=0x00020000
   max_write=0x00100000
   max_background=0
   congestion_threshold=0
   time_gran=1
   unique: 2, success, outsize: 80
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2993
unique: 6, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 12818
unique: 8, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 12845
unique: 10, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 12844
unique: 12, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2517
`
Any one have any ideas as to what's failing?

**Comment by cycomanic** [comment]
I think you're on the new sync API, pretty much all libraries interfacing with the remarkable cloud seem to have trouble with this. Currently only [rmapi](https://github.com/juruen/rmapi) seems to have experimental support for the new API. There was also some work by the rmapy guys (https://github.com/subutux/rmapy/pull/26 ) but that seems to have stalled.

**Comment by nikolaishields** [comment]
Thanks for the context @cycomanic
